name: Create PR from t1 to main

on:
  workflow_dispatch: 

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: t1
          title: "Merge t1 into main"
          body: "This PR was automatically created by GitHub Actions."
          
