name: Create PR from t1 to main

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches are fetched

      - name: Create Pull Request
        uses: peter-evans/pull-request-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: t1
          title: "Merge t1 into main"
          body: "This PR was automatically created by GitHub Actions."
          labels: "automated-pr"
          draft: false  # Set to true if you want the PR to be a draft
