name: Create Pull Request

on:
  workflow_dispatch:  

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Make Changes
        run: |
          echo "Some changes" >> changes.txt
          git add .
          git commit -m "Automated changes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          base: main 
          title: "Automated Pull Request"
          body: "This is an automated PR created by GitHub Actions."
          labels: "automation, bot"
          assignees: "your-username"

