name: tester

on:
  workflow_dispatch

jobs: 
  test:
      runs-on: ubuntu-latest
      steps:
        - name: this should fail
          id: failed
          continue-on-error: true
          run: exit 1
        - name: this should not fail
          id: success
          run: |
            if [ "$(steps.failed.outcome)" == failed ]; {
                echo "THIS SHOULD NOT FAIL"
            }
            else {
                echo "THIS SHOULD HAVE FAILED"
                exit 1
            }
            fi
