name: TEST
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - num: 10
            result: "success"
          - num: 11
            result: "success"
    steps:
      - name: check
        id: testing
        continue-on-error: true
        env:
          INPUTS: ${{ matrix.num }}
        run: |
          if [ "$INPUTS" = 10 ]; then 
              exit 0
          else 
            exit 1
          fi

      - name: Check outcome
        env: 
          OUTPUT: ${{ matrix.result }}
          PREV_STEP_OUTCOME: ${{ steps.testing.outcome }}
        run: |
          if [ "$PREV_STEP_OUTCOME" = "$OUTPUT" ]; then
            echo "The Test Has Passed"
          else
            echo "The Test has Failed"
            exit 1
          fi
