name: testing

on:
  pull_request:
    branches:
      - 'main'

jobs: 
  test:
    strategy:
      matrix:
        include:
           - a: 10
             b: 2
           - a: 12
             b: 0
           - a: 9
             b: 3
    uses: Pritam1729/testing2/.github/workflows/work.yml@main 
    with:
      a: ${{matrix.a}}
      b: ${{matrix.b}}
