name: work 

on:
    pull_request:
        branches: 
            - main

jobs: 
    TEST:
        if: startsWith(github.head_ref, 'oneday')
        runs-on: ubuntu-latest
        steps:
            - name: one
              run: echo "${{ github.head_ref }}" "${{ github.base_ref }}"
