name: work 

on:
    workflow_call: 
        inputs:
            test:
                required: true
                type: number

jobs: 
    build_the_repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

    test: 
        runs-on: ubuntu-latest
        needs: [build_the_repo]
        steps: 
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Make script executable
              run: chmod +x bash.sh

            - name: Run test script
              run: ./bash.sh "$TEST_VALUE"
              env:
                TEST_VALUE: ${{ inputs.test }}
